[build]
  base = "travelguru-fullstack-POSTGRESQL/travelguru-fullstack/frontend"
  command = "npm install && npm run build"
  publish = "travelguru-fullstack-POSTGRESQL/travelguru-fullstack/frontend/dist"

[build.environment]
  VITE_API_URL = "https://travelguru-production.up.railway.app"
